name: Node setup

inputs:
  node-version:
    default: '24'
    type: string

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - run: npm i
      shell: bash
