name: Setup Cloud Environment

runs:
  using: "composite"
  steps:
    - name: Clone terraform scripts repository
      uses: actions/checkout@v4
      with:
        repository: codeparce/terraform-cloud
        ref: main
        token: ${{ secrets.PERSONAL_ACCES_TOKEN }}
        path: terraform-cloud

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Install Doppler CLI
      uses: dopplerhq/cli-action@v3