# .github/workflows/node-build.yml
name: Deploy to Azure Arquitecture


on:
  workflow_call:


jobs:
  deploy-azure-arquitecture:
    name: Arquitecture
    runs-on: ubuntu-latest
    env:
      GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
      DOPPLER_CONFIG: ${{ github.ref_name }}_${{ github.event.repository.name }}
      DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Clone terraform scripts repository
        uses: actions/checkout@v4
        with:
          repository: codeparce/azure-terraform
          ref: azure
          token: ${{ secrets.PERSONAL_ACCES_TOKEN }}
          path: azure-terraform

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v3
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Deploy Azure infrastructure
        run: |
          cd azure-terraform/2-static-web-app
          bash main.sh

      - name: Upload Static Web App secrets artifact
        uses: actions/upload-artifact@v4
        with:
          name: static-web-app-json
          path: azure-terraform/2-static-web-app/secret
          retention-days: 1
