name: Fullstack Pipeline

on:
  workflow_call:
    inputs:
      type:
        required: true
        type: string
      cloud:
        type: string
      services:
        type: string

jobs:
  build:
    uses: ./.github/workflows/ci-build-node.yml
    with:
      doppler-project: vault-codeparce
    secrets: inherit
    
  publish:
    needs: build
    uses: ./.github/workflows/ci-docker.yml
    with:
      target: dist
    secrets: inherit

  infra:
    needs: publish
    uses: ./.github/workflows/infra-az-cae.yml
    secrets: inherit