name: Deploy to Azure Arquitecture

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: codeparce/ci-workflows/.github/actions/node/setup@v1
        with:
          node-version: ${{ inputs.node-version }}

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: dist

      - name: Download config
        uses: actions/download-artifact@v4
        with:
          name: static-web-app-json
          path: secret

      - name: Deploy
        uses: codeparce/ci-workflows/.github/actions/azure/swa@v1
        with:
          artifact-path: dist
          config-path: secret