# .github/workflows/node-build.yml
name: Deploy to Azure Arquitecture

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
      artifact-path:
        type: string
        required: true
      swa_key:
        type: string
        required: true

jobs:
  deploy-az-swa:
    runs-on: ubuntu-latest
    env:
      ENV_NAME: ${{ github.ref_name == 'main' && 'production' || github.ref_name }}
    name: Static Web App
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: dist

      # - name: Download config
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: static-web-app-json
      #     path: secret

      - name: Install SWA CLI
        run: npm install -g @azure/static-web-apps-cli

      # - name: Debug info
      #   run: | 
      #     ls -la 
      #     echo "ENV_NAME=$ENV_NAME"
      #     cat ./secret/static-web-app-json.json
      #     ls -la ./dist

      - name: Deploy Static Web App
        run: |
          swa deploy ./dist --deployment-token ${{ inputs.swa_key }} --env $ENV_NAME