



  build:
    uses: ./.github/workflows/ci-build-node.yml
    with:
      doppler-project: vault-codeparce
    secrets: inherit

  infra:
    if: ${{ inputs.stack == 'front' }}
    uses: ./.github/workflows/infra-az-swa.yml
    secrets: inherit

  deploy:
    if: ${{ inputs.stack == 'front' }}
    uses: ./.github/workflows/cd-az-swa.yml
    with:
      node-version: 24
    needs: [build, infra]
    secrets: inherit