name: Fullstack Pipeline

on:
  workflow_call:
    inputs:
      type:
        required: true
        type: string
      cloud:
        type: string
      services:
        type: string

jobs:
  build:
    uses: ./.github/workflows/ci-build-node.yml
    with:
      doppler-project: vault-codeparce
    secrets: inherit

  infra:
    uses: ./.github/workflows/infra-az-swa.yml
    secrets: inherit

  deploy:
    uses: ./.github/workflows/cd-az-swa.yml
    with:
      node-version: 24
    needs: [build, infra]
    secrets: inherit
