# .github/workflows/node-build.yml
name: Deploy to Azure Arquitecture

on:
  workflow_call:
    inputs:
      tf-directory:
        required: true
        type: string
      cloud:
        required: true
        type: string

jobs:
  terraform:
    name: Arquitecture
    timeout-minutes: 4
    outputs:
      swa_key: ${{ steps.get_key.outputs.swa_key }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy infrastructure
        uses: codeparce/ci-workflows/.github/actions/terraform@v1
        with:
          cloud: ${{ inputs.cloud }}
          tf-directory: ${{ inputs.tf-directory }}
          personal-access-token: ${{ secrets.PERSONAL_ACCES_TOKEN }}
          docker-account-name: ${{ secrets.DOCKER_ACCOUNT_NAME }}
          docker-access-token: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}

      # - name: Upload Static Web App secrets artifact
      #   if: ${{ inputs.tf-directory == '2-static-web-app' }}
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: static-web-app-json
      #     path: terraform-cloud/azure/2-static-web-app/secret
      #     retention-days: 1

      - id: get_key
        if: ${{ inputs.tf-directory == '2-static-web-app' }}
        run: |
          API_KEY=$(jq -r '.properties.apiKey' terraform-cloud/azure/2-static-web-app/secret/static-web-app-json.json)

          echo "$API_KEY" >> $GITHUB_OUTPUT