# .github/workflows/node-build.yml
name: Deploy to Azure Arquitecture

on:
  workflow_call:
    inputs:
      tf-directory:
        required: true
        type: string
      cloud:
        required: true
        type: string
    outputs:
      swa_key:
        description: "Static Web App API Key"
        value: ${{ jobs.terraform.outputs.swa_key }}
        
jobs:
  terraform:
    name: Arquitecture
    #timeout-minutes: 4
    outputs:
      swa_key: ${{ steps.get_key.outputs.swa_key }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy infrastructure
        uses: codeparce/ci-workflows/.github/actions/terraform@v1
        with:
          cloud: ${{ inputs.cloud }}
          tf-directory: ${{ inputs.tf-directory }}
          personal-access-token: ${{ secrets.PERSONAL_ACCES_TOKEN }}
          docker-account-name: ${{ secrets.DOCKER_ACCOUNT_NAME }}
          docker-access-token: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}

      - id: get_key
        name: Get SWA API Key
        if: ${{ inputs.tf-directory == '2-static-web-app' }}
        run: |
          API_KEY=$(jq -r '.properties.apiKey' ./terraform-cloud/azure/2-static-web-app/secret/static-web-app-json.json)

          echo "swa_key=$API_KEY" >> $GITHUB_OUTPUT