# .github/workflows/node-build.yml
name: Deploy to Azure Arquitecture

on:
  workflow_call:

jobs:
  terraform:
    name: Arquitecture
    timeout-minutes: 4
    runs-on: ubuntu-latest
    env:
      GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
      DOCKER_ACCOUNT_NAME: ${{ secrets.DOCKER_ACCOUNT_NAME }}
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
      APP_ENVIRONMENT: ${{ github.ref_name }}_${{ github.event.repository.name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v3


      - name: Clone terraform scripts repository
        uses: actions/checkout@v4
        with:
          repository: codeparce/terraform-cloud
          ref: main
          token: ${{ secrets.PERSONAL_ACCES_TOKEN }}
          path: terraform-cloud

      - name: Deploy Azure infrastructure
        run: |
          cd terraform-cloud/azure/2-static-web-app
          bash main.sh

      - name: Upload Static Web App secrets artifact
        uses: actions/upload-artifact@v4
        with:
          name: static-web-app-json
          path: terraform-cloud/azure/2-static-web-app/secret
          retention-days: 1