name: Fullstack Pipeline

on:
  workflow_call:
    inputs:
      type:
        required: true
        type: string
      cloud:
        type: string
      services:
        type: string

jobs:

  front:
    if: ${{ inputs.type == 'front' }}
    uses: ./.github/workflows/front-${{ inputs.type }}.yml
    secrets: inherit

  back:
    if: ${{ inputs.type == 'back' }}
    uses: ./.github/workflows/back-${{ inputs.type }}.yml
    secrets: inherit


