name: Fullstack Pipeline

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

jobs:
  build:
    uses: ./.github/workflows/ci-build-node.yml
    with:
      node-version: ${{ inputs.node-version }}
      doppler-project: vault-codeparce
    secrets: inherit

  infra:
    uses: ./.github/workflows/infra-az-swa.yml
    secrets: inherit

  deploy:
    uses: ./.github/workflows/cd-az-swa.yml
    with:
      node-version: ${{ inputs.node-version }}
    needs: [build, infra]
    secrets: inherit