name: Fullstack Pipeline

on:
  workflow_call:
    inputs:
      cloud:
        required: true
        type: string


jobs:
  build:
    uses: ./.github/workflows/ci-build-node.yml
    with:
      doppler-project: vault-codeparce
    secrets: inherit

  infra:
    uses: ./.github/workflows/infra.tf.yml
    with:
      tf-directory: 2-static-web-app
      cloud: ${{ inputs.cloud }}
    secrets: inherit

  deploy:
    uses: ./.github/workflows/cd.az.swa.yml
    with:
      swa_key: ${{ needs.infra.outputs.swa_key }}
      config-path: secret
      artifact-path: dist
    needs: [build, infra]
    secrets: inherit
